ticwisite/ticwiapp/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    #url(r'^language/(?P<language>[a-z\-]+)/$', 'article.views.language'),
    #url(r'^like/(?P<article_id>\d+)/$', 'article.views.like_article'),
    #url(r'^search/$', 'article.views.search_titles'),
    #url(r'^api/', include(article_resource.urls)),

    #courses
    url(r'^get_one_course/(?P<course_id>\d+)/$', 'ticwiapp.views.get_one_course'),
    url(r'^all_courses/$', 'ticwiapp.views.all_courses'),
    url(r'^create_course/$', 'ticwiapp.views.create_course'),
    url(r'^edit_course/(?P<course_id>\d+)/$', 'ticwiapp.views.create_course'),
    url(r'^update_course/$', 'ticwiapp.views.update_course'),
    url(r'^delete_course/(?P<course_id>\d+)$', 'ticwiapp.views.delete_course'),
    url(r'^add_presenter/(?P<course_id>\d+)/$', 'ticwiapp.views.add_presenter'),
    url(r'^add_presenter_now/(?P<course_id>\d+)/(?P<user_id>\d+)/$', 'ticwiapp.views.add_presenter_now'),
    url(r'^add_participant/(?P<course_id>\d+)/$', 'ticwiapp.views.add_participant'),
    url(r'^add_participant_now/(?P<course_id>\d+)/(?P<user_id>\d+)/$', 'ticwiapp.views.add_participant_now'),
    url(r'^remove_participant/(?P<course_id>\d+)/(?P<user_id>\d+)/$', 'ticwiapp.views.remove_participant'),   
    url(r'^remove_presenter/(?P<course_id>\d+)/(?P<user_id>\d+)/$', 'ticwiapp.views.remove_presenter'),
    url(r'^search_course/$', 'ticwiapp.views.search_course'),
    url(r'^add_comment/(?P<course_id>\d+)/$', 'ticwiapp.views.add_comment'),

    #Tics
    url(r'^add_tic/(?P<course_id>\d+)/(?P<user_type>\d+)/$', 'ticwiapp.views.add_tic'),
    url(r'^get_one_tic/(?P<tic_id>\d+)/$', 'ticwiapp.views.get_one_tic'),

    #Course Commments
    url(r'^change_course_comment_access/(?P<course_id>\d+)/(?P<comment_id>\w+)/$', 'ticwiapp.views.change_course_comment_access'),
    url(r'^search_user/$', 'ticwiapp.views.search_user'),

    #inbox
    url(r'^send_message/(?P<user_id>\d+)/(?P<sender_id>\w+)/$', 'ticwiapp.views.send_message'),
    
    #desktop
    url(r'^inst_desktop/$', 'ticwiapp.views.inst_desktop'),
    url(r'^user_desktop/$', 'ticwiapp.views.user_desktop'),
    url(r'^desktop/$', 'ticwiapp.views.desktop'),

)

ticwisite/ticwisite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import settings

urlpatterns = patterns('',
    (r'^ticwiapp/', include('ticwiapp.urls')),
    (r'^userprofile/', include('userprofile.urls')),
 
   # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # user auth urls
    url(r'^accounts/login/$',  'ticwisite.views.login'),
    url(r'^accounts/auth/$',  'ticwisite.views.auth_view'),
    url(r'^accounts/logout/$', 'ticwisite.views.logout'),
    url(r'^accounts/loggedin/$', 'ticwisite.views.loggedin'),
    url(r'^accounts/invalid/$', 'ticwisite.views.invalid_login'),
    url(r'^accounts/register/$', 'ticwisite.views.register_user'),
    url(r'^accounts/register_success/$', 'ticwisite.views.register_success'),


    url(r'^accounts/register_success/$', 'userprofile.views.redirect_to_desktop'),
    url(r'^accounts/go_home/$', 'ticwisite.views.go_home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if not settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

ticwisite/ticwiapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class TicCategory(models.Model):
        category        =       models.CharField(max_length=255)

        def __unicode__(self):
                return self.category



class GuiTic(models.Model):
        image           =       models.CharField(max_length=255)



class Course(models.Model):
	name		=	models.CharField(max_length=255)
	date		=	models.DateTimeField('course date')
	description	=	models.CharField(max_length=255)
	importance	=	models.IntegerField()
        user 		= 	models.ForeignKey(User)
	def __unicode__(self):
        	return self.name

course = property(lambda u: Course.objects.get_or_create(name=u)[0])

class Tic(models.Model):
	USER_TYPE = (
    	(1, 'Participant'),
    	(2, 'Presenter'),
  	)
        course          =       models.ForeignKey(Course)
        category        =       models.ForeignKey(TicCategory)
        gui_tic         =       models.ForeignKey(GuiTic)
        user_type	= 	models.CharField( max_length=1 , default="i", choices=USER_TYPE)
        dummy_name  	=       models.CharField(max_length=255)

class CourseProposed(models.Model):
	name		=	models.CharField(max_length=255)
	category	=	models.CharField(max_length=255)
	description	=	models.IntegerField()
	user		=	models.ForeignKey(User)

class InstitutionProfile(models.Model):
        name            =       models.CharField(max_length=255)
        description     =       models.CharField(max_length=255)
        member_since    =       models.DateTimeField()
        email           =       models.CharField(max_length=255)

#class Friend_institution(models.Model):
#	this_institution	=	models.ForeignKey(InstitutionProfile)
#	friend_institution	=	models.ForeignKey(InstitutionProfile)

class UserTic(models.Model):
	user		=	models.ForeignKey(User)
	tic		=	models.ForeignKey(Tic)
	tic_category	=	models.ForeignKey(TicCategory)

class WhoParticipate(models.Model):
	course		=	models.ForeignKey(Course)
	user		=	models.ForeignKey(User)
	approve_tic	=	models.IntegerField()

class WhoPresent(models.Model):
	course	 	=	models.ForeignKey(Course)
	presenter	=	models.ForeignKey(User)


class CourseComment(models.Model):
	ACCESS_CHOICES = (
 	   ('public', 'Public'),
 	   ('private', 'Private'),
	)
	READ_CHOICES = (
           ('yes', 'Yes'),
           ('no', 'No'),
        )

	first_name 	=	models.CharField(max_length=200)
	second_name 	= 	models.CharField(max_length=200)
	body 		= 	models.TextField()
	pub_date 	= 	models.DateTimeField('date published')
	access 		= 	models.CharField(max_length=10, default="private", choices=ACCESS_CHOICES)
	already_read	=	models.CharField(max_length=4, default="no", choices=READ_CHOICES)
	course 		= 	models.ForeignKey(Course)

class  Inbox(models.Model):
        user            =       models.ForeignKey(User)

class InboxMessage(models.Model):
        READ_CHOICES = (
           ('yes', 'Yes'),
           ('no', 'No'),
        )

        body            =       models.TextField()
        already_read    =       models.CharField(max_length=4, default="no", choices=READ_CHOICES)
	pub_date        =       models.DateTimeField('date published')
        sender		= 	models.ForeignKey(User, related_name='inboxmessage_sender') 
	receiver	=	models.ForeignKey(User, related_name='inboxmessage_receiver')                                         

	def __unicode__(self):
               return self.body

ticwisite/ticwiapp/views.py
from django.shortcuts import render_to_response
from ticwiapp.models import Course, User, WhoPresent, WhoParticipate, Tic, CourseComment, Inbox, InboxMessage
from django.http import HttpResponse
from forms import CourseForm, TicForm, CourseCommentForm, InboxMessageForm
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.forms.models import model_to_dict  
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from profilemanager.models import CustomUser
from django.db.models import Q
#from ticwiapp.forms import InboxMessageForm
import forms 

#from haystack.query import SearchQuerySet


class update_course(UpdateView):
    model = Course
    fields = ['name']
    template_name_suffix = '_update_form'
    #return HttpResponseRedirect('/ticwiapp/desktop')

def add_presenter_now(request, course_id=None, user_id=None):

    #If this presenter has not being added to the course, add it.
    current_presenter_obj = WhoPresent.objects.filter(course=course_id, presenter=user_id)
    if not current_presenter_obj:
         #Create an relational object with the course_id and presenter_id
         obj = WhoPresent(course_id = course_id , presenter_id = user_id)    
         obj.save()

    return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id)

def add_presenter(request, course_id=None):
    #Prepare presenters to add 
    args = {}
    args.update(csrf(request))
    #We are going to display just those users that are Participant or Presenter
    #TODO: Add a filter to just show those that have Presenter feature enabled
    args['presenters'] = CustomUser.objects.filter(user_type = "u")
    args['course_id'] = course_id 
    args['full_name'] = request.user.username
    return render_to_response('add_presenter.html', args) 

def add_participant_now(request, course_id=None, user_id=None):
    #If this participant has not being added to the course, add it.
    current_participant_obj= WhoParticipate.objects.filter(course=course_id, user=user_id)
    if not current_participant_obj:
         #Create an relational object with the course_id and presenter_id
         obj = WhoParticipate(course_id = course_id , user_id = user_id, approve_tic='0')
         obj.save()
    #TODO: else Warn the user???
    return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id)

def add_participant(request, course_id=None):
    #Prepare users to add 
    args = {}
    args.update(csrf(request))
    args['participants'] =  CustomUser.objects.filter(user_type = "u")
    args['course_id'] = course_id
    args['full_name'] = request.user.username
    return render_to_response('add_participant.html', args)

def remove_presenter(request, course_id=None, user_id=None):
    obj = WhoPresent.objects.get(course_id = course_id , presenter_id = user_id)
    obj.delete()
    return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id)


def remove_participant(request, course_id=None, user_id=None):
    obj = WhoParticipate.objects.get(course_id = course_id , user_id = user_id)
    obj.delete()
    return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id)


def delete_course(request, course_id=None):
    # Course is detected and is called to delete, 
    # TODO: perhaps it is needed a validation that instance exist and confirmation question! 
    obj = Course.objects.get(id=course_id)
    obj.delete()
    return HttpResponseRedirect('/ticwiapp/desktop')


def all_courses(request):
    #THIS MIGHT BE DEPRECATED, courses.html is included in desktop.html
    #Shows all courses available in a table
    #TODO: Show the list with certain number of items so if there are 1000 split 50 by 50

    #language = 'en-gb'
    #session_language = 'en-gb'

    #if 'lang' in request.COOKIES:
    #    language = request.COOKIES['lang']

    #if 'lang' in request.session:
    #    session_language = request.sessiond['lang']

    args = {}
    args.update(csrf(request))
    #Filter only those that belong to this user :)
    args['courses'] = Course.objects.filter( user = request.user )
    #Follow query gets all unread commentd from all courses
    args['unread_comments'] = CourseComment.objects.filter( course =  Course.objects.filter( user = request.user ), already_read="no" ).count
    # Follow query gets all Inbox unread messages
    args['inbox_messages'] = InboxMessage.objects.filter( receiver =  request.user , already_read="no" ).count
    args['user'] = request.user
    #args['language'] = language
    #args['session_language'] = session_language
    args['full_name'] = request.user.username
    return render_to_response('courses.html', args)

def get_one_course(request, course_id=None):
    # Prepares course information, collecting presenters, participants.
    #course_instance = Course.objects.get( id=course_id )
    who_present_obj = WhoPresent.objects.filter( course_id=course_id )
    #Developer tip: notice that is being used id__in, which gets all objects
    #that were result of who_present_instance query; if it is used id = who_present_instance
    # only the first object will be retrieved excluding all others
    # See:https://docs.djangoproject.com/en/dev/ref/models/querysets/#in
    #presenter_instance = User.objects.filter( id__in=who_present_instance.values('presenter') )

    who_participate_obj = WhoParticipate.objects.filter( course_id=course_id )
    #participant_instance = User.objects.filter( id__in=who_participate_instance.values('user') )

    #We can now say that the Institution has read all the comments by joining the course
    if request.user.user_type == "i":
        CourseComment.objects.filter(course = course_id).update(already_read = "yes")

    #Look for Participants Tic
    participant_tic_obj = Tic.objects.filter( course_id = course_id, user_type = "u")
    args = {}
    args.update(csrf(request))
    args['presenters'] = User.objects.filter( id__in=who_present_obj.values('presenter') ) #presenter_instance
    args['participants'] = User.objects.filter( id__in=who_participate_obj.values('user') ) #participant_instance
    args['course'] = Course.objects.get( id=course_id )
    args['participant_tic'] = Tic.objects.filter( course_id = course_id, user_type = "i")
    args['presenter_tic'] = Tic.objects.filter( course_id = course_id, user_type = "u")
    args['full_name'] = request.user.username
    return render_to_response('course.html',args)
                              
def create_course( request, course_id=None ):

    #Firstst of all we need to make user that non-institutions can't create courses
    if request.user.user_type == "u":
	return HttpResponseRedirect('/ticwiapp/desktop')
    #Prepares the information to update or create a new course.

    #if id:
    #    instance = get_object_or_404(Course, id=course_id)
    #    form = CourseForm(request.POST or None, instance=instance)
    #    if form.is_valid():
    #        form.update()
    #        return HttpResponseRedirect('/ticwiapp/get/')
    #    course = Course.objects.get(id=id)
    #    dictionary = model_to_dict(course, fields=[], exclude=[]) 
    #    form = forms.CourseForm(dictionary)
    #else:
    if request.POST:
        form = CourseForm(request.POST)
        if form.is_valid():
            a = form.save( commit = False )
            a.user = request.user
            a.save()

            return HttpResponseRedirect('/ticwiapp/desktop')
    else:
        form = CourseForm()

    args = {}
    args.update(csrf(request))
    args['form'] = form
    args['full_name'] = request.user.username
    return render_to_response('create_course.html', args)

def add_tic( request, course_id, user_type=None ):
    if request.POST:
        form = TicForm(request.POST)
        if form.is_valid():
            a = form.save()

            return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id+"/"+user_type)
    else:
        form = TicForm()

    args = {}
    args.update(csrf(request))
    args['form'] = form
    args['course_id'] = course_id
    args['user_type'] = user_type
    args['full_name'] = request.user.username
    return render_to_response('add_tic.html', args)

def delete_Tic(request, tic_id, course_id):
    # Tic is detected and is called to delete, 
    # TODO: perhaps it is needed a validation that instance exist and confirmation question! 
    obj = Tic.objects.get(id=tic_id)
    obj.delete()
    return HttpResponseRedirect('/ticwiapp/get_one_course/'+course_id)

def get_one_tic(request, tic_id=None):

    #Look for Participants Tic
    #tic_instance = Tic.objects.get( id = tic_id)
    args = {}
    args.update(csrf(request))
    args['tic'] =  Tic.objects.get( id = tic_id )
    args['full_name'] = request.user.username
    return render_to_response('tic.html',args)

def add_comment(request, course_id):
    a = Course.objects.get(id=course_id)

    if request.method == "POST":
        f = CourseCommentForm(request.POST)
        if f.is_valid():
            c = f.save(commit=False)
            c.pub_date = timezone.now()
            c.course = a
            c.save()
            return HttpResponseRedirect('/ticwiapp/get_one_course/%s' % course_id)
    else:
        f = CourseCommentForm()

    args = {}
    args.update(csrf(request))
    args['course'] = a
    args['form'] = f
    args['full_name'] = request.user.username
    return render_to_response('add_comment.html', args)

def change_course_comment_access(request, course_id, comment_id):
	c = CourseComment.objects.get(id=comment_id)
	if c.access == "private":
		c.access = "public"
	else:
		c.access = "private"
	
	c.save()
	return HttpResponseRedirect('/ticwiapp/get_one_course/%s' % course_id)

def search_user(request):
    #Prepare users to add 
    args = {}
    args.update(csrf(request))
    #TODO: Get all users but himself
    args['users'] =  CustomUser.objects.all()

ticwisite/templates/ticwiapp/add_comment.html
{% extends "base.html" %}

{% load static %}
{% block upbar %}
{% include 'upbar_logged.html' %}
{% endblock upbar %}

{% block content %}

<form action="/ticwiapp/add_comment/{{course.id}}/" method="post">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" name="submit" value="Post Comment">
</form>

{% endblock %}

ticwisite/templates/ticwiapp/add_participant.html
{% extends "base.html" %}
{% load static %}
{% block upbar %}
{% include 'upbar_logged.html' %}
{% endblock upbar %}

{% block content %}

.....<a href="/ticwiapp/get_one_course/{{course_id}}"> Cancel </a>
{% if participants.count > 0 %}

 <TABLE CLASS="MYTABLE">
    <CAPTION CLASS="MYTABLE">Participants</CAPTION>
    
    <THEAD >
      <TR CLASS="MYTABLE">
        <TH CLASS="MYTABLE">Name</TH>
        <TH CLASS="MYTABLE"></TH>
      </TR>
    </THEAD>
    <TBODY>
{% for participant in participants %}
<TR CLASS="MYTABLE">
<TD CLASS="MYTABLE">{{ participant.email }}</TD>
<TD CLASS="MYTABLE"><a href="/ticwiapp/add_participant_now/{{ course_id }}/{{participant.id}}/"> <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/></a></TD>
</TR>

{% endfor %}

 </TBODY>
</TABLE>

{% else %}


<pd>No participants in database!</p>

{% endif %}

{% endblock %}

ticwisite/templates/ticwiapp/add_presenter.html
{% extends "base.html" %}
{% load static %}
{% block upbar %}
{% include 'upbar_logged.html' %}
{% endblock upbar %}

{% block content %}

.....<a href="/ticwiapp/get_one_course/{{course_id}}"> Cancel </a>
{% if presenters.count > 0 %}

 <TABLE CLASS="MYTABLE">
    <CAPTION CLASS="MYTABLE">Users</CAPTION>
    
    <THEAD >
      <TR CLASS="MYTABLE">
        <TH CLASS="MYTABLE">Name</TH>
        <TH CLASS="MYTABLE"></TH>
      </TR>
    </THEAD>
    <TBODY>
{% for presenter in presenters %}
<TR CLASS="MYTABLE">
<TD CLASS="MYTABLE">{{ presenter.email }}</TD>
<TD CLASS="MYTABLE"><a href="/ticwiapp/add_presenter_now/{{ course_id }}/{{presenter.id}}/"> <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/></a></TD>

</TR>

{% endfor %}

 </TBODY>
</TABLE>

{% else %}


<pd>No users in database!</p>

{% endif %}

{% endblock %}

ticwisite/templates/ticwiapp/course.html
{% extends "base.html" %}
{% load static %}

{% block upbar %}
{% include 'upbar_logged.html' %}
{% endblock upbar %}


{% block content %}

<p>
<a href="/ticwiapp/edit_course/{{course.id}}"> Edit </a>...
<a href="/ticwiapp/desktop"> Desktop  </a>...
<a href="/ticwiapp/update_course"> Update </a>...
<a href="/ticwiapp/delete_course/{{course.id}}"> Delete </a> ....
</p>

 <TABLE CLASS="MYTABLE">

     <THEAD >
        <TR CLASS="MYTABLE">
        <TH CLASS="MYTABLE">General Information:</TH>
      </TR>
    </THEAD>
    <TBODY>

        <TR CLASS="MYTABLE"><TD CLASS="MYTABLE">Course Name: <b>{{ course.name }}</b></TD></TR>
        <TR CLASS="MYTABLE"><TD CLASS="MYTABLE">Description: {{ course.description }}</TD></TR>
        <TR CLASS="MYTABLE"><TD CLASS="MYTABLE">Date: {{ course.date}} </TD></TR>
        </TR>

     </TBODY>
</TABLE>

<br><br>

<TABLE CLASS="MYTABLE">
        <CAPTION CLASS="MYTABLE">Presenters: {{ presenters.count  }}
        <a href="/ticwiapp/add_presenter/{{course.id}}">
        <img src=" {% static  "assets/images/new_icon_text.jpg" %} " width=30/>
        <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/></a></CAPTION>


{% if presenters.count > 0 %}

     <THEAD >
        <TR CLASS="MYTABLE">
        <TH CLASS="MYTABLE">Name</TH>
        <TH CLASS="MYTABLE">Email</TH>
        <TH CLASS="MYTABLE"></TH>
      </TR>
    </THEAD>
    <TBODY>

    {% for presenter in presenters %}
        <TR CLASS="MYTABLE">
        <TD CLASS="MYTABLE">{{ presenter.username }}</TD>
        <TD CLASS="MYTABLE">{{ presenter.email }}</TD>
        <TD CLASS="MYTABLE">
        <a href="/ticwiapp/remove_presenter/{{ course.id }}/{{ presenter.id }}"><img src=" {% static  "assets/images/remove_icon.png" %} " width=20/></a></TD>
        
        </TR>
    {% endfor %}

     </TBODY>

{% else %}
    <TBODY>
    <TD CLASS="MYTABLE">
        <img src=" {% static  "assets/images/alert_icon.jpg" %} " width=30/>
        No presenters registered!
    </TD>
    </TBODY>
{% endif %}

</TABLE>

<br><br>


    <TABLE CLASS="MYTABLE">
        <CAPTION CLASS="MYTABLE">Participants: {{ participants.count  }}
        <a href="/ticwiapp/add_participant/{{course.id}}">
        <img src=" {% static  "assets/images/new_icon_text.jpg" %} " width=30/>
        <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/></a></CAPTION>

{% if participants.count > 0 %}

     <THEAD >
        <TR CLASS="MYTABLE">
        <TH CLASS="MYTABLE">Name</TH>
        <TH CLASS="MYTABLE">Email</TH>
        <TH CLASS="MYTABLE"></TH>
      </TR>
    </THEAD>
    <TBODY>
    
    {% for participant in participants %}
        <TR CLASS="MYTABLE">
        <TD CLASS="MYTABLE">  {{ participant.username }}</TD>
        <TD CLASS="MYTABLE">{{ participant.email }}</TD>
        <TD CLASS="MYTABLE"> 
        <a href="/ticwiapp/remove_participant/{{ course.id }}/{{ participant.id }}"><img src=" {% static  "assets/images/remove_icon.png" %} " width=20/></a></TD>
        </TR>
    {% endfor %}

     </TBODY>

{% else %}
    <TBODY>
    <TD class="MYTABLE">
          <img src=" {% static  "assets/images/alert_icon.jpg" %} " width=30/>
          No participants registered!
    </TD>
    </TBODY>
{% endif %}
    
    </TABLE>


<br><br>


{% if participant_tic.count > 0 %}


    {% for participant_t in participant_tic %}
           <p>participant_tic exist:  {{ participant_t.id }}  <a href="/ticwiapp/get_one_tic/{{ participant_t.id }}">Edit... </a>
        <a href="/ticwiapp/delete_tic/{{ participant_t.id }}"><img src=" {% static  "assets/images/remove_icon.png" %} " width=20/></a></p>
    {% endfor %}

{% else %}
      <p>    <img src=" {% static  "assets/images/alert_icon.jpg" %} " width=30/>
          No participants Tic registered!  <a href="/ticwiapp/add_tic/{{course.id}}/1">
         <img src=" {% static  "assets/images/new_icon_text.jpg" %} " width=30/>
         <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/>
         </a>
      </p>
{% endif %}


<br><br>

{% if presenter_tic.count > 0 %}

    {# We are expecting just one iteration in follow for#}
    {% for presenter_t in presenter_tic %}
           <p>presenter_tic exist:  {{ presenter_t.id }}  <a href="/ticwiapp/get_one_tic/{{ presenter_t.id }}">Edit... </a>
        <a href="/ticwiapp/delete_tic/{{ presenter_t.id }}"><img src=" {% static  "assets/images/remove_icon.png" %} " width=20/></a></p>
    {% endfor %}

{% else %}
      <p>    <img src=" {% static  "assets/images/alert_icon.jpg" %} " width=30/>
          No presenter Tic registered!  <a href="/ticwiapp/add_tic/{{course.id}}/2">
         <img src=" {% static  "assets/images/new_icon_text.jpg" %} " width=30/>
         <img src=" {% static  "assets/images/add_new_icon.png" %} " width=15/>
         </a>
      </p>
{% endif %}


<h2>Comments</h2>
{% for c in course.coursecomment_set.all %}
<p>{{c.first_name}}: {{c.second_name}} Said: {{c.body}} -- access: {{c.access}} already_read: {{c.already_read}} </p>
{% if c.access = "private" %}
<a href="/ticwiapp/change_course_comment_access/{{ course.id }}/{{ c.id }}">Make Public </a>
{% else %}
<a href="/ticwiapp/change_course_comment_access/{{ course.id }}/{{ c.id }}">Make private</a>
{% endif %}
</p>
{% endfor %}

<p><a href="/ticwiapp/add_comment/{{course.id}}">Add Comment</a></p>



{% endblock %}

ticwisite/templates/ticwiapp/create_course.html
{% extends "base.html" %}


{% block upbar %}
{% include 'upbar_logged.html' %}
{% endblock upbar %}



{% block content %}

<a href="/ticwiapp/desktop">Cancel</a>

<form action="/ticwiapp/create_course/" method="post" enctype="multipart/form-data">{% csrf_token %}
<ul>
{{form.as_ul}}
</ul>

<input type="submit" name="submit" value="Create Course">
</form>
{% endblock %}